### ISSUE TITLE
CUDA will not load in Julia 0.4

### ISSUE THREAD

**Issue by mattcbro** [JuliaAttic/CUDA.jl#10]
Here are the symptoms:

julia> using CUDA

WARNING: deprecated syntax "(Int=>ASCIIString)[a=>b, ...]" at /home/matthew/.julia/v0.4/CUDA/src/errors.jl:62.
Use "Dict{Int,ASCIIString}(a=>b, ...)" instead.
CUDA Driver Initialized
WARNING: int(x) is deprecated, use Int(x) instead.
 in depwarn at deprecated.jl:73
 in int at deprecated.jl:50
 in driver_version at /home/matthew/.julia/v0.4/CUDA/src/base.jl:29
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
while loading /home/matthew/.julia/v0.4/CUDA/src/base.jl, in expression starting on line 32
ERROR: LoadError: LoadError: TypeError: Tuple: in parameter, expected Type{T}, got Tuple{DataType,DataType}
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
while loading /home/matthew/.julia/v0.4/CUDA/src/execution.jl, in expression starting on line 4
while loading /home/matthew/.julia/v0.4/CUDA/src/CUDA.jl, in expression starting on line 42

**Comment by sfchen** [comment]
Same issue in v0.5

**Comment by ranjanan** [comment]
@sfchen @mattcbro I've just sent a pull request #11 that fixes this.
