### ISSUE TITLE
Move over to JuliaLang

### ISSUE THREAD

**Issue by lindahua** [JuliaAttic/CUDA.jl#3]
As my focus is now on statistical packages, I don't think I have enough time to keep up with the maintenance of this package. 

Since, this package may serve as the foundation of future development of CUDA-based projects/packages and some GSOC projects. I propose to move the ownership over to JuliaLang. 

cc: @StefanKarpinski, @ViralbShah

**Comment by ViralBShah** [comment]
Should we do it at a point when there is someone else maintaining it? Just being lazy.

**Comment by ivarne** [comment]
I don't have a good understanding of the state of CUDA.jl, but as there are currently only 1 contributor (that does not want to do maintenance), it does not look like pulverizing the responsibility is a good way forward. I don't think it is a good idea to have half finished projects under the JuliaLang organisation, because they somehow looks like blessed packages with a broad community backing and supporting it.

**Sorry for the inadvertent post early post, for those who get email.**

**Comment by lindahua** [comment]
Let me explain a little bit about my reasons to propose this move:
1. The package is definitely not full featured. But it has necessary features ready & works in not too complex cases.
2. The contributions have become more active recently. There is some ongoing discussion in the issues. And I just merged a PR before writing this post.
3. I will definitely continue to maintain this package, but mainly for bug fixes at this point and with a slower pace. (My focus is now more on the statistical packages).  However, this package is a foundational package, which would provide support for higher level packages for GPU computing. It is also the base for one of the GSoC projects. 

As I see this an important package for the future (as GPU computing becomes increasingly popular), I would like to see it get broader support & more active maintenance, instead of having its development hindered by my limited availability of time. Having it under JuliaLang will make others easier to contribute to it, instead of going through the PR every time.

**Comment by StefanKarpinski** [comment]
I wonder if there should be a JuliaGPU organization to act as an umbrella for all the various GPU efforts. I feel like having everything under a single organization, though not significant per se helps push the packages towards unification and cooperation.

**Comment by lindahua** [comment]
The package has been moved over to JuliaGPU
